### PR TITLE
Allow custom configurability of segment variables

### PR DESCRIPTION
**Pull request by sausin**
Current implementation assumes input from `config` for segment size variables. However, this may not always be convenient. This PR allows for downstream packages to have their own implementation for input to these parameters.

### CODE REVIEW

**Comment by mzur** [comment]
Can you please give an example when this may not be "convenient"? It should be easy to update the config in a downstream package.

**Comment by sausin** [comment]
@mzur Sure!

The downstream package I have takes input for common variables (authentication details) to operate as a config file in laravel. If input is required via `config` variable, then the same would need to be specified at upload time.

However, if I use the laravel configuration variables then I can just get them _one time_ when configuring the package and these values would then not need to be provided at every upload location in code.

**Comment by mzur** [comment]
I don't understand, sorry. I maintain such a "downstream package" myself ([here](https://github.com/mzur/laravel-openstack-swift)). All [configuration variables](https://github.com/mzur/laravel-openstack-swift#configuration) can simply be set in the storage disk configuration array. How is your example any different to this?

**Comment by sausin** [comment]
@mzur You're right. Closing PR :+1:

**Pull request closed without merging**
